async function renderAdmin(view, root) {
  const map={dashboard:adminDashboard,members:adminMembers,stock:adminStock,flavours:adminFlavours,materials:adminMaterials,purchases:adminPurchases,expenses:adminExpenses,sales:adminSales,invoices:adminInvoices,accounting:adminAccounting,partners:adminPartners,posters:adminPosters,audit:adminAudit};
  return (map[view]||adminDashboard)(root);
}

async function adminDashboard(root){
  const {data,error}=await state.supabase.rpc('admin_dashboard_summary');if(error)throw error;const s=data?.[0]||{};
  root.innerHTML=pageHead('ADMIN','Dashboard WAHH AIR','Pusat kawalan operasi, stok, jualan dan accounting.')+`<div class="kpi-grid">${kpi('Sales Hari Ini',money(s.today_sales))}${kpi('Unit Hari Ini',num(s.today_units))}${kpi('Active Rider/Ejen',num(s.active_members))}${kpi('Total Stok Air',`${num(s.total_stock)} unit`)}</div><div class="grid-2"><section class="panel"><div class="panel-head"><div><h3>Bulan Ini</h3><p>Management P&L semasa.</p></div><button class="btn soft sm" data-view="accounting">Accounting</button></div><div class="grid-2">${kpi('Revenue',money(s.month_revenue))}${kpi('Net Profit',money(s.month_net_profit))}</div></section><section class="panel"><div class="panel-head"><div><h3>Tindakan Pantas</h3><p>Operasi harian.</p></div></div><div class="grid-2"><button class="btn primary" data-view="stock">Manage Stock</button><button class="btn ghost" data-view="sales">Update Jualan</button><button class="btn ghost" data-view="purchases">Belian Stock</button><button class="btn ghost" data-view="invoices">Invoices</button></div></section></div>`;
}

async function adminMembers(root){
  const {data,error}=await state.supabase.rpc('admin_list_members');if(error)throw error;
  root.innerHTML=pageHead('ADMIN','Rider / Ejen','Admin melihat Public ID dan maklumat operasi, bukan Auth UUID atau password.')+`<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Public ID</th><th>Nama</th><th>Telefon</th><th>Role</th><th>Status</th><th>Daftar</th><th>Tindakan</th></tr></thead><tbody>${data?.length?data.map(r=>`<tr><td><strong>${esc(r.public_id)}</strong></td><td>${esc(r.full_name)}</td><td>${esc(r.phone||'-')}</td><td><span class="role-badge">${esc(r.role)}</span></td><td><span class="status-badge ${esc(r.status)}">${esc(r.status)}</span></td><td>${dateMY(r.created_at)}</td><td><div class="row-actions" style="margin:0;justify-content:flex-start"><button class="btn sm ghost member-status" data-id="${esc(r.public_id)}" data-status="${r.status==='active'?'suspended':'active'}">${r.status==='active'?'Suspend':'Aktifkan'}</button><button class="btn sm danger member-delete" data-id="${esc(r.public_id)}">Delete</button></div></td></tr>`).join(''):tableEmpty(7)}</tbody></table></div></section>`;
  $$('.member-status',root).forEach(b=>b.addEventListener('click',()=>updateMemberStatus(b.dataset.id,b.dataset.status)));
  $$('.member-delete',root).forEach(b=>b.addEventListener('click',()=>deleteMember(b.dataset.id)));
}
async function updateMemberStatus(publicId,status){const ok=await confirmAction('Tukar status akaun?',`${publicId} akan ditetapkan sebagai ${status}.`);if(!ok)return;const{error}=await state.supabase.rpc('admin_set_member_status',{p_public_id:publicId,p_status:status});if(error)return toast(error.message,'error');toast('Status dikemas kini.','success');renderView('members');}
async function deleteMember(publicId){const ok=await confirmAction('Delete akaun?',`Akaun ${publicId} akan dipadam daripada Authentication dan database. Tindakan ini tidak boleh dibatalkan.`);if(!ok)return;const token=state.session.access_token;const res=await fetch('/api/admin-delete-user',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({publicId})});const out=await res.json().catch(()=>({}));if(!res.ok)return toast(out.error||'Delete gagal.','error');toast(`${publicId} telah dipadam.`,'success');renderView('members');}

async function adminStock(root){
  const [{data:stock,error},{data:members},{data:flavours}]=await Promise.all([state.supabase.rpc('admin_stock_summary'),state.supabase.rpc('admin_list_members'),state.supabase.from('flavours').select('id,name,active').eq('active',true).order('name')]);if(error)throw error;
  const userOpts=(members||[]).filter(x=>x.status==='active').map(x=>`<option value="${esc(x.public_id)}">${esc(x.public_id)} — ${esc(x.full_name)}</option>`).join('');
  const flOpts=(flavours||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
  root.innerHTML=pageHead('INVENTORY','Stok Air','HQ stock, production, allocation Rider/Ejen dan correction semuanya direkod dalam stock movement.')+`<section class="panel"><div class="panel-head"><div><h3>Hasilkan Stok Air</h3><p>Production akan consume bahan ikut Recipe dan tambah stok siap ke HQ.</p></div></div><form id="produceForm" class="inline-form"><div class="field"><label>Perisa</label><select id="prodFlavour">${flOpts}</select></div><div class="field"><label>Qty Siap</label><input id="prodQty" type="number" min="1" required placeholder="cth 50"></div><div class="field"><label>Nota</label><input id="prodReason" value="Production"></div><button class="btn primary" type="submit">Produce</button></form></section>
  <section class="panel"><div class="panel-head"><div><h3>Stock Correction HQ</h3><p>Untuk stok siap dibeli dari luar, kiraan awal atau correction. Nilai positif tambah, negatif tolak.</p></div></div><form id="hqStockForm" class="inline-form"><div class="field"><label>Perisa</label><select id="hqFlavour">${flOpts}</select></div><div class="field"><label>Perubahan Qty</label><input id="hqQty" type="number" required placeholder="cth 10 / -5"></div><div class="field"><label>Sebab</label><input id="hqReason" required placeholder="Stock count correction"></div><button class="btn ghost" type="submit">Update HQ</button></form></section>
  <section class="panel"><div class="panel-head"><div><h3>Allocate Stock</h3><p>Pindahkan stok HQ kepada Rider/Ejen.</p></div></div><form id="allocateForm" class="inline-form"><div class="field"><label>Rider/Ejen</label><select id="allocMember">${userOpts}</select></div><div class="field"><label>Perisa</label><select id="allocFlavour">${flOpts}</select></div><div class="field"><label>Qty</label><input id="allocQty" type="number" min="1" required></div><button class="btn primary" type="submit">Allocate</button></form></section>
  <section class="panel"><div class="panel-head"><div><h3>Return Stock</h3><p>Pulangkan baki stok Rider/Ejen ke HQ, contohnya sebelum akaun ditamatkan.</p></div></div><form id="returnForm" class="inline-form"><div class="field"><label>Rider/Ejen</label><select id="returnMember">${userOpts}</select></div><div class="field"><label>Perisa</label><select id="returnFlavour">${flOpts}</select></div><div class="field"><label>Qty</label><input id="returnQty" type="number" min="1" required></div><button class="btn ghost" type="submit">Return ke HQ</button></form></section>
  <section class="panel"><div class="panel-head"><div><h3>Current Stock</h3><p>HQ + semua lokasi Rider/Ejen.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Lokasi</th><th>Nama</th><th>Perisa</th><th class="num">Qty</th></tr></thead><tbody>${stock?.length?stock.map(r=>`<tr><td><strong>${esc(r.location_code)}</strong></td><td>${esc(r.location_name)}</td><td>${esc(r.flavour_name)}</td><td class="num">${num(r.quantity)}</td></tr>`).join(''):tableEmpty(4)}</tbody></table></div></section>`;
  $('#produceForm',root).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;setBusy(b,true,'Producing...');const{error}=await state.supabase.rpc('admin_produce_stock',{p_flavour_id:$('#prodFlavour').value,p_quantity:Number($('#prodQty').value),p_reason:$('#prodReason').value.trim()||'Production'});setBusy(b,false);if(error)return toast(error.message,'error');toast('Production siap. Bahan ditolak dan stok HQ ditambah.','success');renderView('stock');});
  $('#hqStockForm',root).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;setBusy(b,true);const{error}=await state.supabase.rpc('admin_adjust_hq_stock',{p_flavour_id:$('#hqFlavour').value,p_quantity_change:Number($('#hqQty').value),p_reason:$('#hqReason').value.trim()});setBusy(b,false);if(error)return toast(error.message,'error');toast('Stok HQ dikemas kini.','success');renderView('stock');});
  $('#allocateForm',root).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;setBusy(b,true);const{error}=await state.supabase.rpc('admin_allocate_stock',{p_public_id:$('#allocMember').value,p_flavour_id:$('#allocFlavour').value,p_quantity:Number($('#allocQty').value)});setBusy(b,false);if(error)return toast(error.message,'error');toast('Stock berjaya dialokasikan.','success');renderView('stock');});
  $('#returnForm',root).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;setBusy(b,true);const{error}=await state.supabase.rpc('admin_return_stock',{p_public_id:$('#returnMember').value,p_flavour_id:$('#returnFlavour').value,p_quantity:Number($('#returnQty').value)});setBusy(b,false);if(error)return toast(error.message,'error');toast('Stok berjaya dipulangkan ke HQ.','success');renderView('stock');});
}

async function adminFlavours(root){
  const{data,error}=await state.supabase.from('flavours').select('*').order('created_at');if(error)throw error;
  root.innerHTML=pageHead('PRODUCT','Perisa & Harga','Tambah perisa, harga jual, minimum stok dan manual COGS fallback.')+`<section class="panel"><form id="flavourForm" class="inline-form"><div class="field"><label>Nama Perisa</label><input id="flName" required placeholder="Honeydew"></div><div class="field"><label>Harga Jual RM</label><input id="flPrice" type="number" min="0" step="0.01" required value="5"></div><div class="field"><label>Manual COGS RM</label><input id="flCogs" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Low Stock</label><input id="flLow" type="number" min="0" value="10"></div><button class="btn primary" type="submit">Tambah</button></form></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Perisa</th><th class="num">Harga</th><th class="num">Manual COGS</th><th class="num">Low Stock</th><th>Status</th></tr></thead><tbody>${data?.length?data.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td class="num">${money(r.selling_price)}</td><td class="num">${money(r.manual_unit_cogs)}</td><td class="num">${num(r.low_stock_threshold)}</td><td><button class="btn sm ${r.active?'success':'ghost'} flavour-toggle" data-id="${r.id}" data-active="${!r.active}">${r.active?'Active':'Inactive'}</button></td></tr>`).join(''):tableEmpty(5)}</tbody></table></div></section>`;
  $('#flavourForm',root).addEventListener('submit',async e=>{e.preventDefault();const slug=$('#flName').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const{error}=await state.supabase.from('flavours').insert({name:$('#flName').value.trim(),slug,selling_price:Number($('#flPrice').value),manual_unit_cogs:Number($('#flCogs').value),low_stock_threshold:Number($('#flLow').value)});if(error)return toast(error.message,'error');toast('Perisa ditambah.','success');await loadPublic();renderView('flavours');});
  $$('.flavour-toggle',root).forEach(b=>b.addEventListener('click',async()=>{const{error}=await state.supabase.from('flavours').update({active:b.dataset.active==='true'}).eq('id',b.dataset.id);if(error)return toast(error.message,'error');toast('Status perisa dikemas kini.','success');await loadPublic();renderView('flavours');}));
}
