async function adminMaterials(root){
  const [{data:materials,error},{data:flavours},{data:recipes}]=await Promise.all([state.supabase.from('materials').select('*').order('name'),state.supabase.from('flavours').select('id,name').eq('active',true).order('name'),state.supabase.from('recipes').select('id,qty_required,flavour_id,material_id,flavours(name),materials(name,unit)').order('created_at')]);if(error)throw error;
  root.innerHTML=pageHead('COSTING','Bahan & Recipe','Average cost bahan berubah bila belian baru direkod. Recipe digunakan untuk kira COGS per unit.')+`<section class="panel"><div class="panel-head"><div><h3>Tambah Bahan</h3></div></div><form id="matForm" class="inline-form"><div class="field"><label>Nama</label><input id="matName" required placeholder="Serbuk Honeydew"></div><div class="field"><label>Unit</label><select id="matUnit"><option value="g">gram (g)</option><option value="ml">ml</option><option value="unit">unit</option><option value="can">tin</option><option value="kg">kg</option></select></div><div class="field"><label>Min Qty</label><input id="matMin" type="number" min="0" step="0.001" value="0"></div><button class="btn primary" type="submit">Tambah</button></form></section>
  <section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Bahan</th><th>Unit</th><th class="num">Current Qty</th><th class="num">Avg Cost / Unit</th><th class="num">Nilai</th></tr></thead><tbody>${materials?.length?materials.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${esc(r.unit)}</td><td class="num">${num(r.current_qty,3)}</td><td class="num">${money(r.avg_unit_cost)}</td><td class="num">${money(Number(r.current_qty)*Number(r.avg_unit_cost))}</td></tr>`).join(''):tableEmpty(5)}</tbody></table></div></section>
  <section class="panel"><div class="panel-head"><div><h3>Recipe / Product Costing</h3><p>Contoh: 15g serbuk untuk 1 botol Honeydew.</p></div></div><form id="recipeForm" class="inline-form"><div class="field"><label>Perisa</label><select id="recFlavour">${(flavours||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Bahan</label><select id="recMaterial">${(materials||[]).map(x=>`<option value="${x.id}">${esc(x.name)} (${esc(x.unit)})</option>`).join('')}</select></div><div class="field"><label>Qty / 1 unit air</label><input id="recQty" type="number" min="0.0001" step="0.0001" required></div><button class="btn primary" type="submit">Tambah Recipe</button></form><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Perisa</th><th>Bahan</th><th class="num">Qty</th><th></th></tr></thead><tbody>${recipes?.length?recipes.map(r=>`<tr><td>${esc(r.flavours?.name||'-')}</td><td>${esc(r.materials?.name||'-')}</td><td class="num">${num(r.qty_required,4)} ${esc(r.materials?.unit||'')}</td><td><button class="btn sm danger recipe-delete" data-id="${r.id}">Delete</button></td></tr>`).join(''):tableEmpty(4)}</tbody></table></div></section>`;
  $('#matForm',root).addEventListener('submit',async e=>{e.preventDefault();const{error}=await state.supabase.from('materials').insert({name:$('#matName').value.trim(),unit:$('#matUnit').value,min_qty:Number($('#matMin').value)});if(error)return toast(error.message,'error');toast('Bahan ditambah.','success');renderView('materials');});
  $('#recipeForm',root).addEventListener('submit',async e=>{e.preventDefault();const{error}=await state.supabase.from('recipes').upsert({flavour_id:$('#recFlavour').value,material_id:$('#recMaterial').value,qty_required:Number($('#recQty').value)},{onConflict:'flavour_id,material_id'});if(error)return toast(error.message,'error');toast('Recipe dikemas kini.','success');renderView('materials');});
  $$('.recipe-delete',root).forEach(b=>b.addEventListener('click',async()=>{const{error}=await state.supabase.from('recipes').delete().eq('id',b.dataset.id);if(error)return toast(error.message,'error');renderView('materials');}));
}

async function adminPurchases(root){
  const[{data:materials,error},{data:rows}]=await Promise.all([state.supabase.from('materials').select('id,name,unit').eq('active',true).order('name'),state.supabase.rpc('admin_purchase_history',{p_limit:100})]);if(error)throw error;
  root.innerHTML=pageHead('ACCOUNTING','Belian Stok Baru','Belian bahan menambah inventory asset dan recalculates weighted-average cost.')+`<section class="panel"><form id="purchaseForm" class="inline-form"><div class="field"><label>Bahan</label><select id="purMat">${(materials||[]).map(x=>`<option value="${x.id}">${esc(x.name)} (${esc(x.unit)})</option>`).join('')}</select></div><div class="field"><label>Qty</label><input id="purQty" type="number" min="0.0001" step="0.0001" required></div><div class="field"><label>Unit Cost RM</label><input id="purCost" type="number" min="0" step="0.0001" required></div><div class="field"><label>Supplier</label><input id="purSupplier" placeholder="Nama supplier"></div><button class="btn primary" type="submit">Rekod Belian</button></form></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tarikh</th><th>Bahan</th><th>Supplier</th><th class="num">Qty</th><th class="num">Unit Cost</th><th class="num">Total</th></tr></thead><tbody>${rows?.length?rows.map(r=>`<tr><td>${dateMY(r.purchased_at)}</td><td>${esc(r.material_name)}</td><td>${esc(r.supplier||'-')}</td><td class="num">${num(r.quantity,3)} ${esc(r.unit)}</td><td class="num">${money(r.unit_cost)}</td><td class="num">${money(r.total_cost)}</td></tr>`).join(''):tableEmpty(6)}</tbody></table></div></section>`;
  $('#purchaseForm',root).addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;setBusy(b,true);const{error}=await state.supabase.rpc('admin_record_material_purchase',{p_material_id:$('#purMat').value,p_quantity:Number($('#purQty').value),p_unit_cost:Number($('#purCost').value),p_supplier:$('#purSupplier').value.trim()||null,p_notes:null});setBusy(b,false);if(error)return toast(error.message,'error');toast('Belian stok direkod dan average cost dikemas kini.','success');renderView('purchases');});
}

async function adminExpenses(root){
  const{data,error}=await state.supabase.from('expenses').select('*').order('incurred_at',{ascending:false}).limit(100);if(error)throw error;
  const cats=['Rental','Petrol','Delivery','Electricity','Packaging','Marketing','Equipment','Maintenance','Other'];
  root.innerHTML=pageHead('ACCOUNTING','Expenses','Perbelanjaan operasi ditolak dalam pengiraan net profit.')+`<section class="panel"><form id="expenseForm" class="inline-form"><div class="field"><label>Category</label><select id="expCat">${cats.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Amount RM</label><input id="expAmount" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Description</label><input id="expDesc" required></div><div class="field"><label>Date</label><input id="expDate" type="date" value="${todayISO()}" required></div><button class="btn primary" type="submit">Tambah</button></form></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tarikh</th><th>Category</th><th>Description</th><th class="num">Amount</th></tr></thead><tbody>${data?.length?data.map(r=>`<tr><td>${dateMY(r.incurred_at)}</td><td>${esc(r.category)}</td><td>${esc(r.description)}</td><td class="num">${money(r.amount)}</td></tr>`).join(''):tableEmpty(4)}</tbody></table></div></section>`;
  $('#expenseForm',root).addEventListener('submit',async e=>{e.preventDefault();const{error}=await state.supabase.from('expenses').insert({category:$('#expCat').value,amount:Number($('#expAmount').value),description:$('#expDesc').value.trim(),incurred_at:new Date(`${$('#expDate').value}T12:00:00`).toISOString()});if(error)return toast(error.message,'error');toast('Expense ditambah.','success');renderView('expenses');});
}

async function adminSales(root){
  const[{data:rows,error},{data:members},{data:stock}]=await Promise.all([state.supabase.rpc('admin_sales_list',{p_limit:150}),state.supabase.rpc('admin_list_members'),state.supabase.rpc('admin_stock_summary')]);if(error)throw error;
  const active=(members||[]).filter(x=>x.status==='active');
  root.innerHTML=pageHead('SALES','Jualan Semua Rider/Ejen','Admin boleh finalize jualan bagi pihak Rider/Ejen. Invoice tetap dijana automatik.')+`<section class="panel"><div class="panel-head"><div><h3>Admin Update Jualan</h3><p>Pilih member dahulu; stok mereka akan digunakan.</p></div></div><form id="adminSaleForm"><div class="inline-form"><div class="field"><label>Rider/Ejen</label><select id="asMember"><option value="">Pilih...</option>${active.map(x=>`<option value="${esc(x.public_id)}">${esc(x.public_id)} — ${esc(x.full_name)}</option>`).join('')}</select></div><button class="btn ghost" type="button" id="loadMemberStock">Load Stok</button></div><div id="adminSaleLines" class="sale-lines" style="margin-top:14px"></div><label class="field-label" style="margin-top:12px">Nota<textarea id="adminSaleNotes" class="field-input" rows="2"></textarea></label><div class="row-actions"><button class="btn primary" type="submit">Finalize Untuk Member</button></div></form></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tarikh</th><th>Invoice</th><th>Seller</th><th>Status</th><th>Commission</th><th class="num">Sales</th><th class="num">COGS</th><th class="num">Net WAHH</th><th>Tindakan</th></tr></thead><tbody>${rows?.length?rows.map(r=>`<tr><td>${dateMY(r.sale_date)}</td><td>${esc(r.invoice_no||'-')}</td><td><strong>${esc(r.public_id)}</strong><br><span class="muted">${esc(r.seller_name)}</span></td><td><span class="status-badge ${r.status==='finalized'?'active':'terminated'}">${esc(r.status)}</span></td><td>${esc(r.commission_status)}<br><span class="muted">${money(r.commission_amount)}</span></td><td class="num">${money(r.total_amount)}</td><td class="num">${money(r.total_cogs)}</td><td class="num">${money(r.net_to_business)}</td><td>${r.status==='finalized'&&r.invoice_no?`<div class="row-actions" style="margin:0;justify-content:flex-start"><button class="btn sm ghost comm-status" data-no="${esc(r.invoice_no)}" data-status="approved">Approve</button><button class="btn sm success comm-status" data-no="${esc(r.invoice_no)}" data-status="paid">Paid</button></div>`:''}</td></tr>`).join(''):tableEmpty(9)}</tbody></table></div></section>`;
  $('#loadMemberStock',root).addEventListener('click',async()=>{const pid=$('#asMember').value;if(!pid)return toast('Pilih Rider/Ejen.','warning');const{data,error}=await state.supabase.rpc('admin_get_member_stock',{p_public_id:pid});if(error)return toast(error.message,'error');$('#adminSaleLines').innerHTML=(data||[]).map(r=>`<div class="sale-line" data-flavour="${r.flavour_id}" data-price="${r.selling_price}" data-stock="${r.quantity}"><div class="line-name"><strong>${esc(r.flavour_name)}</strong><div class="price">Stok: ${num(r.quantity)} • ${money(r.selling_price)}</div></div><div><input class="sale-qty" type="number" min="0" max="${r.quantity}" value="0"></div><div class="price line-total">${money(0)}</div></div>`).join('')||'<div class="empty-state">Tiada stok.</div>';$$('.sale-qty',$('#adminSaleLines')).forEach(i=>i.addEventListener('input',recalcSale));});
  $('#adminSaleForm',root).addEventListener('submit',async e=>{e.preventDefault();const pid=$('#asMember').value;if(!pid)return toast('Pilih member.','warning');const items=$$('#adminSaleLines .sale-line').map(line=>({flavour_id:line.dataset.flavour,quantity:Number($('.sale-qty',line).value||0)})).filter(x=>x.quantity>0);if(!items.length)return toast('Masukkan jualan.','warning');const ok=await confirmAction('Finalize jualan?',`Jualan akan direkod untuk ${pid} dan invoice akan dijana.`);if(!ok)return;const b=e.submitter;setBusy(b,true);const{data,error}=await state.supabase.rpc('admin_finalize_sale',{p_public_id:pid,p_items:items,p_notes:$('#adminSaleNotes').value.trim()||null});setBusy(b,false);if(error)return toast(error.message,'error');toast(`Jualan selesai. Invoice ${data?.[0]?.invoice_no||''}.`,'success');renderView('sales');});
  $$('.comm-status',root).forEach(b=>b.addEventListener('click',async()=>{const{error}=await state.supabase.rpc('admin_set_commission_status',{p_invoice_no:b.dataset.no,p_status:b.dataset.status});if(error)return toast(error.message,'error');toast(`Komisen ${b.dataset.no} → ${b.dataset.status}.`,'success');renderView('sales');}));
}

async function adminInvoices(root){
  const{data,error}=await state.supabase.rpc('admin_invoice_list',{p_limit:200});if(error)throw error;
  root.innerHTML=pageHead('INVOICE','Invoice Center','Invoice hanya boleh dilihat Admin. Jualan finalized menjana invoice snapshot secara automatik.')+`<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Tarikh</th><th>Seller</th><th>Status</th><th class="num">Sales</th><th class="num">Commission</th><th></th></tr></thead><tbody>${data?.length?data.map(r=>`<tr><td><strong>${esc(r.invoice_no)}</strong></td><td>${dateMY(r.created_at)}</td><td>${esc(r.seller_public_id)}<br><span class="muted">${esc(r.seller_name)}</span></td><td><span class="status-badge ${r.status==='issued'?'active':'terminated'}">${esc(r.status)}</span></td><td class="num">${money(r.total_sales)}</td><td class="num">${money(r.commission_amount)}</td><td><div class="row-actions" style="margin:0;justify-content:flex-start"><button class="btn sm ghost invoice-view" data-no="${esc(r.invoice_no)}">Buka</button>${r.status==='issued'?`<button class="btn sm danger invoice-void" data-no="${esc(r.invoice_no)}">Void</button>`:''}</div></td></tr>`).join(''):tableEmpty(7)}</tbody></table></div></section>`;
  $$('.invoice-view',root).forEach(b=>b.addEventListener('click',()=>openInvoice(b.dataset.no)));
  $$('.invoice-void',root).forEach(b=>b.addEventListener('click',async()=>{const reason=window.prompt(`Sebab void ${b.dataset.no}:`);if(!reason?.trim())return;const ok=await confirmAction('Void invoice?',`${b.dataset.no} akan dibatalkan dan stok dipulangkan kepada seller.`);if(!ok)return;const{error}=await state.supabase.rpc('admin_void_invoice',{p_invoice_no:b.dataset.no,p_reason:reason.trim()});if(error)return toast(error.message,'error');toast('Invoice berjaya di-void.','success');renderView('invoices');}));
}
